### ISSUE TITLE
dev environment: automate setup of host (Linux VM, WSL or macOS)

### ISSUE THREAD

**Issue by hunchback** [IBM/the-mesh-for-data#127]
When setting up a new host of the-mesh-for-data development, there are many non automated steps one has to do including setup of host packages, go etc.

These need to include:
1. all the VM setup steps done on travis which enable running all CI tests
2. setup of go development environment

the relevant section in travis which should be replicated on host setup:

```
language: go

services:
- docker

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - asciidoctor
      - conntrack
      - ethtool
      - apache2-utils
  hosts:
  - kind-registry

os:
- linux

go:
- "1.13"
```
