### ISSUE TITLE
Update documentation for modules

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#143]
- Documentation should reflect the code
- Improve documentation in Overview pages
- Add documentation to contribution guide

_Originally posted by @roee88 in https://github.com/IBM/the-mesh-for-data/issues/111#issuecomment-720472090_

**Comment by roee88** [comment]
@shlomitk1 please verify that there are no mistakes and it does reflect the current codebase

**Comment by shlomitk1** [comment]
name, namespace and labels are under metadata. 
```
metadata:
  labels: {}
  name: c98add937fd49f52da10
  namespace: m4d-lh4wn
read:
  - assetID: ...
```
